openapi: 3.0.0

info:
  title: {{title}}
  version: {{version}}
  description: 我的api接口


servers:
  - url: http://localhost:8099/v1

paths:
  /auth/login:
    post:
      summary: login user
      operationId: methods.auth.login
      requestBody:
        description: user info
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginUser"
      responses:
        '200':
          description: JWT token
          content:
            'text/plain':
              schema:
                type: string

  /:
    get:
      summary: index 页面
      operationId: methods.index.index
      responses:
        '200':
          description: index页面
          content:
            'text/plain':
              schema:
                type: string

  /hello:
    get:
      summary: hello
      operationId: methods.index.hello
      responses:
        '200':
          description: say hello
          content:
            'application/json':
              schema:
                type: string
      security:
        - jwt: ['secret']

components:
  securitySchemes:
    jwt:
      type: http
      scheme: bearer
      bearerFormat: JWT
      x-bearerInfoFunc: methods.auth.decode_token

  schemas:
    LoginUser:
      required:
        - username
        - password
      properties:
        username:
          type: string
          example: username
        password:
          type: string
          example: password
